restqa/restqa

package-lock.json, package.json
Bump version of restqapi in order to handle ssl certificate validation
=> Ssl certificate

bin/restqa, package.json, src/cli/steps.js, src/cli/steps.test.js, src/config/index.js, src/config/index.test.js, src/config/schema.js
=> CLI :  command line to get step definition

bin/restqa, package.json, src/cli/index.js, src/cli/install.js, src/cli/install.test.js, src/index.js, src/index.test.js
=> CLI :  new command restqa install

package.json, src/cli/install.js, src/cli/install.test.js
=> Discord install

package.json, src/cli/install.js, src/cli/install.test.js
=> New Addons : for data management

package.json, src/cli/install.js, src/cli/install.test.js
=> New output addon : http-html-report

src/cli/generate.js, src/cli/generate.test.js
=> Fix bug on CLI generate command

bin/restqa, package.json, src/restqa-snippet.js, src/restqa-snippet.test.js
=> Create a cucumber snipet synthax to help user when a step is undefined

src/setup.js, src/utils/logger.js, src/utils/logger.test.js
=> Add a warning message when the http-html-report is configured with the

bin/restqa, src/cli/run.js, src/cli/run.test.js, src/index.js, src/index.test.js
=> Enable new option to handle gherkin tags on th the CLI : restqa run

CHANGELOG.md
=> Initiate the CHANGELOG #53

src/cli/install.js, src/cli/install.test.js
Add new output report to install:
* Html: `restqa install html`
* File: `restqa install fine`
=> CLI: Install report

.github/workflows/build.yml, src/cli/initialize.js, src/cli/initialize.test.js, src/cli/install.test.js, src/cli/run.test.js, src/cli/steps.test.js, src/config/index.test.js
Let's run improve the continuous improvement flow by adding a step to run the test on a windows container
=> Improve windows compatibility

CHANGELOG.md, CONTRIBUTING.md, README.md, bin/restqa, bin/tests/common.sh, bin/tests/install.bats, package-lock.json, package.json, src/cli/install.js, src/cli/install.test.js
Enable installation of line messenger as an alerting channel through the command line : `restqa install line`
=> Line alerting

CHANGELOG.md, src/bootstrap.js, src/bootstrap.test.js, src/cli/steps.js, src/config/schema.js
=> Feat: enable the timeout option

CHANGELOG.md, package-lock.json, package.json, src/restqa-formatter.js
Let's add a custom text just before we export the information 😇
=> feat: Update the text on the cucumber export

CHANGELOG.md, package-lock.json, package.json
Related to https://github.com/restqa/restqapi/pull/66
=> feat: Generate artillery performance test scenario from restqa test

CHANGELOG.md, bin/restqa, package-lock.json, package.json, src/config/schema.js, src/restqa-formatter.js, src/restqa-formatter.test.js, src/utils/welcome.js, src/utils/welcome.test.js
Let share some tips along the way with testing.
=> Random friendly tips

package.json, src/cli/dashboard.js, src/cli/dashboard.test.js, src/index.js, src/index.test.js
In order to open more options for the user, let's expose the dashboard server as a method
=> Module dashboard

.gitignore, bin/restqa, src/cli/index.js, src/index.js
Reduce the starting time by half using lazy loading.
=> Performance improvement

CHANGELOG.md, bin/tests/install.bats, src/cli/install.js, src/cli/install.test.js, src/locales/en.yml, src/locales/index.js, src/locales/index.test.js
Create the command to install a webhook (https://docs.restqa.io/alerting/webhook)
```
restqa install webhook
```
=> feat: add the command to install a new webhook

dashboard/src/components/restqa/project-init/RestQAProjectInit.vue, dashboard/src/components/restqa/sponsors/RestQASponsors.vue
Add utm info to url and fix typo.
=> add utm + typo

dashboard/src/components/restqa/sponsors/RestQASponsors.test.js
fix unit tests, add utm info, fix typo
=> add utm info + fix typo

src/cli/initialize.js, src/cli/initialize.test.js, src/locales/en.yml
Delete the "description" field from init questions.
=> feat: delete description question from init

.vscode/settings.json, bin/program.js, bin/restqa, bin/tests/run.bats, package-lock.json, src/cli/initialize.js, src/cli/run.js, src/cli/run.test.js, src/http-server/controllers.js, src/http-server/index.test.js, src/index.js
=> feat(run): run Init before run if no config file

src/cli/initialize.js, src/cli/initialize.test.js, src/http-server/index.test.js
Hi 👋 
This PULL request fixes issue #178
=> fix: disable description check in Initialize.generate

dashboard/package-lock.json, dashboard/package.json
=> Revert "chore(deps): bump prismjs from 1.23.0 to 1.25.0 in /dashboard"

cli/src/config/preference.js, cli/src/config/preference.test.js, cli/src/utils/telemetry/index.js, cli/src/utils/telemetry/index.test.js, cli/src/utils/telemetry/provider.js
Store a local file on the user computer to enable customs preferences.
=> Store user Preferences

ui/src/components/restqa/project-editor/runner/step/RestQAProjectEditorRunnerStep.scss, ui/src/components/restqa/project-editor/runner/step/RestQAProjectEditorRunnerStep.vue, ui/src/components/restqa/project-editor/runner/step/StepFormat.vue
In order to show a better test report let's show up the tables and inline arguments
Fix #232
=> feat: Enable table display on the table and inline arguments on the UI

docs/content/cli.md, docs/content/local-testing/_index.md, docs/content/test-creation/given/authorization.md, docs/content/test-creation/given/host.md, docs/content/test-creation/given/query.md, docs/content/test-creation/given/request-body-form.md, docs/content/test-creation/given/request-body-json.md, docs/content/test-creation/given/request-headers.md, docs/content/test-creation/then/contract-validation.md, docs/content/test-creation/then/cookies.md, docs/content/test-creation/then/dataset.md, docs/content/test-creation/then/date.md, docs/content/test-creation/then/headers.md, docs/content/test-creation/then/json-body.md, docs/content/test-creation/then/latency.md, docs/content/test-creation/then/sort-numeric.md, docs/content/test-creation/then/status.md, docs/content/test-creation/when/send.md, ui/src/components/restqa/documentation/Render.vue
In order to provide a better UX experience we would like to provide a pre-requisit
Fix #234
=> UI/Doc: add pre-requisite on the documentation pages

CONTRIBUTING.md, package-lock.json, package.json
Improve the contribution experience.
=> Devexp: Add the npm run contribute command

ui/index.html
Since firefox has issue to open the test report... Let's add small hack
Fix #243
=> fix: add a small hack to get the report to load on firefox

packages/report-ui/src/components/restqa/specification/Specification.vue, packages/report-ui/src/layouts/partials/Footer.vue
Fix the issue of the swagger collection that misbehave on the Report UI.
Fix #270
=> [Report UI] Fix:  swagger collection misbehavior

packages/cli/package.json, packages/cli/src/cli/run.js, packages/cli/src/cli/run.test.js, packages/cli/src/core/initialize.js, packages/cli/src/formatters/export-formatter.js, packages/report-ui/index.cjs, packages/report-ui/public/restqa.result.js, packages/report-ui/src/components/restqa/collection/Tool.vue, packages/report-ui/src/components/restqa/http-mock/HttpMock.vue, packages/report-ui/src/components/restqa/performance/Performance.vue, packages/report-ui/src/services/result.js, packages/report-ui/src/views/coverage/Coverage.vue
Since the report ui could be used to as file:// or http:// , we converted all the absolute url to relative urls
Fix #262
=> [UI] fix: absolute path -> relative path for file that needs to be

.github/scripts/sync-version.sh, .github/workflows/publish.yml
Challenges of monorepo is the packages version... Let's fix that! 
Fix #267
=> CI: Create a script to sync all the package version with the main

.github/workflows/publish.yml
=> CI: enable the publication of pre-release through github

packages/plugin-http-mock/src/http-mock/index.js, packages/plugin-http-mock/src/index.js
- fix timeout issue with test containers
- add more logs
=> fix: increase default boot timeout

packages/plugin-mongodb-mock/src/index.js, packages/plugin-mongodb-mock/src/mongodb-mock/index.js
-  increase boot timeout for mongo mock plugin
- add tips log
Fix #1
=> fix: increase boot timeout for mongo mock plugin

packages/screenshot/.eslintrc, packages/screenshot/.gitignore, packages/screenshot/.prettierrc, packages/screenshot/.restqa.yml, packages/screenshot/README.md, packages/screenshot/bin/index.js, packages/screenshot/package.json, packages/screenshot/src/index.js, packages/screenshot/src/services/browser.js, packages/screenshot/tests/check.js, packages/screenshot/tests/local/get.feature, packages/screenshot/tests/server.js, packages/screenshot/tests/steps.cjs, pnpm-lock.yaml
> New package that allowing to create a screenshot of the test report using the command `npx @restqa/screenshot`. It aims to be used by the github action.
=> package: ew package @restqa/screenshot

packages/report-ui/public/restqa.result.js, packages/report-ui/src/services/history.js
Since we are storing the test result on the local storage, let's ensure that the result are not mix between different microservice
Fix #286
=> Fix: Historical conflict - Report ui

packages/cli/package.json, pnpm-lock.yaml
> Let's give a try to [Scarf-js ](https://github.com/scarf-sh/scarf-js)
Fix #313
=> Spike: use scarf-js to track adoption

packages/cli/package.json, packages/cli/src/core/initialize.js, packages/cli/src/core/plugin.js, packages/core-git/.eslintrc, packages/core-git/.gitignore, packages/core-git/.prettierrc, packages/core-git/package.json, packages/core-git/restqa, packages/core-git/src/contributors.js, packages/core-git/src/ignore.js, packages/core-git/src/index.js, packages/core-git/src/utils/process.js, packages/core-git/tests/contributors.test.js, packages/core-git/tests/ignore.test.js, pnpm-lock.yaml
Let's update the gitgnore while we are onboarding a project into RestQA
Fix #278
=> Feature: update the gitignore while onboarding RestQA into a project

packages/core-performance/src/utils/api.js, packages/core-performance/src/vendors/artillery.js, packages/core-performance/tests/artillery.test.js, packages/plugin-rest-api/src/rest-api/lib/api/response.js
> Artillery handle the case when the API response does not contain a body
=> Fix: Artillery fixture generation if there is no content-type

packages/core-collection/src/vendors/postman.js, packages/core-collection/tests/fixtures/authorization-basic-auth/postman.json, packages/core-collection/tests/fixtures/authorization-bearer/postman.json, packages/core-collection/tests/fixtures/base-url/postman.json, packages/core-collection/tests/fixtures/headers/postman.json, packages/core-collection/tests/fixtures/query-strings/postman.json, packages/core-collection/tests/fixtures/request-body-form/postman.json, packages/core-collection/tests/fixtures/request-body-json/postman.json
> Fix small bug on postman collection generation
=> fix: The host variable on the postman collection

packages/cli/src/core/plugin.test.js, packages/core-microservice/package.json, packages/core-microservice/src/index.js, packages/core-microservice/src/utils/process.js, packages/core-microservice/tests/fixture/server-coverage.js, packages/core-microservice/tests/fixture/server-envs.js, packages/core-microservice/tests/fixture/server-timeout.js, packages/core-microservice/tests/fixture/server.js, packages/core-microservice/tests/index.test.js, pnpm-lock.yaml
> Let's try to fix a major stability issues. While RestQA get shutdown suddenly the child process remain orphan and blocking another run of RestQA.
Fix #252
=> fix: Kill microservice if a process signal is received

packages/cli/src/formatters/export-formatter.js
> Fix footer version on the report.
Fix #287
=> fix: version of RestQA on the report-ui

packages/cli/src/core/initialize.js, packages/cli/src/core/initialize.test.js
> Let put a friendly name for the initial scenario generated.
Fix #329
=> feat: change the feature name of the initial scenario generated

README.md
> Let's add a diagram in the README to explain what happened under the scene
Fix #324
=> Doc: Add diagram to the README

packages/plugin-mongodb-mock/README.md, packages/plugin-mongodb-mock/src/index.cjs, packages/plugin-mongodb-mock/src/mongodb-mock/index.cjs, packages/plugin-mongodb-mock/tests/features/mongodb-mock.feature, packages/plugin-mongodb-mock/tests/server.js
> Add the inserted entries into the data state - plugin mongo db
Fix #333
=> feat: Add the inserted entries into the data state - plugin mongo db

.github/workflows/first-good-issue-comment.yml
> Let's publish a tweet every time we have an issue tagged as `good first issue`
Fix #265
=> CI: Tweet when an issues has been tagged has 'good first issue'

packages/cli/bin/restqa.js, packages/cli/src/cli/run.js, packages/cli/src/cli/run.test.js, packages/cli/src/core/plugin.js, packages/cli/src/utils/process.js, packages/core-logger/src/index.js, packages/core-microservice/src/index.js, packages/core-specification/src/swagger/index.js, packages/plugin-mongodb-mock/README.md, packages/plugin-mongodb-mock/src/mongodb-mock/index.cjs, packages/plugin-mongodb-mock/tests/features/cast-data.feature, packages/plugin-mongodb-mock/tests/features/step-definition.feature, packages/plugin-mongodb-mock/tests/server.js, packages/report-ui/index.html
Let allow the cast of data while inserting the data from the scenario on the mongo database.
Fix #332
=> Feat: Mongdb data cast

packages/cucumber-export/src/format.js
> Fix skip scenario on the UI report
Fix #341
=> fix: the skipped scenario should not be counted as fail scenarios

packages/report-ui/src/views/coverage/Coverage.vue
> Fix the test coverage load on windows.
Fix #340
=> fix: On window the test coverage iframe should be able to load

packages/plugin-mongodb-mock/README.md, packages/plugin-mongodb-mock/src/mongodb-mock/index.cjs, packages/plugin-mongodb-mock/tests/features/cast-data.feature, packages/plugin-mongodb-mock/tests/features/step-definition.feature, packages/plugin-mongodb-mock/tests/server.js
=> feat: Enabling retrieving search id in dataset

packages/cli/src/restqa-snippet.js
=> fix: Undefined step definition link broken

packages/report-ui/src/components/restqa/contributors/RestQAContributors.vue, packages/report-ui/src/components/restqa/test-report/FeatureScenarios.vue, packages/report-ui/src/views/testReport/Feature.vue, pnpm-lock.yaml
=> feat: let's reshape the state panel of the feature detail

docs/test-creation/dataset/_index.md, packages/plugin-rest-api/src/rest-api/steps/2-when/functions.js, packages/plugin-rest-api/src/rest-api/steps/2-when/functions.test.js, packages/sandbox/tests/local/sandbox-console.feature, packages/sandbox/tests/local/sandbox-file.feature
=> feat: add the response information in the dataset

packages/report-ui/src/components/restqa/test-report/steps/Step.vue, packages/report-ui/src/components/restqa/test-report/steps/StepFormat.vue
=> UI: Enable display of custom table

packages/report-ui/src/components/UI/highcharts/Highcharts.vue, packages/report-ui/src/components/restqa/documentation/Search.vue, packages/report-ui/src/components/restqa/history/Widget.vue, packages/report-ui/src/views/Homepage.vue, packages/report-ui/src/views/documentation/Page.vue
In order to propose the changed by @rezaalmanda on this issue #381.
I would like to propose the following:
Fix #381
=> Feat:  [UI] Update the history panel to show a bar chart

packages/report-ui/package.json, packages/report-ui/src/components/restqa/documentation/Search.vue, packages/report-ui/src/layouts/partials/SideBar.vue, packages/report-ui/src/views/documentation/Page.vue, pnpm-lock.yaml
Let's get the search bar more accessible by putting it on the top of the documentation.
Fix #378
=> [UI] Change position of the documentation Search bar

packages/docs/src/index.js, packages/report-ui/src/views/documentation/Page.vue
In order to ease the navigation, lets add a "previous" and "Next" at the bottom of each documentation page
Fix #369
=> [UI] feat: add navigation on the documentation pages

packages/cucumber-export/README.md, packages/report-ui/src/services/history.js
small fix on the cucumber-export package
=> Fix cucumber export
